"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var book_1 = require("./book");
var library_1 = require("./library");
var book1 = new book_1.Book("Segismundo y compania", 120, "15040gfg", "Fernando Lalana", "Calcetin Tejero");
var book2 = new book_1.Book("Yerma", 200, "posd54", "Federico Garcia Lorca", "Elche");
var book3 = new book_1.Book("La vida es sueno", 300, "150pn600", "Calderon de la Barca", "Anaya");
var book4 = new book_1.Book("La casa de Bernarda Alba", 200, "29pj15", "Federico Garcia Lorca", "Santillana");
var coleccionLibros = [book1, book2, book3, book4];
var bibloteca1 = new library_1.Library(coleccionLibros, "Leopoldo Queipo", "Jose Mena");
console.log("La direccion es: " + bibloteca1.getAddress());
console.log("El manager es: " + bibloteca1.getManager());
console.log("Los datos completos son: " + bibloteca1.toString());
console.log("El numero de libros es: " + bibloteca1.getNumberOfBooks());
console.log("Estos libros son de Lorca: " + bibloteca1.findByAuthor("Federico Garcia Lorca"));
bibloteca1.setAddress("Musico Granados");
bibloteca1.setManager("Juan Rios");
console.log("La nueva direccion es: " + bibloteca1.getAddress());
console.log("El nuevo manager es: " + bibloteca1.getManager());
